services:
  postgres:
    image: postgres:18.1-trixie
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./configs/postgres:/docker-entrypoint-initdb.d
    env_file:
      - .env.build
    networks:
      - docker-net
    restart: unless-stopped
    expose:
      - 5432

  pg-exporter-mlflow:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: pg-exporter-mlflow
    expose:
      - 9187
    restart: unless-stopped
    networks:
      - docker-net
    env_file:
      - .env.build
    environment:
      - DATA_SOURCE_URI=postgres.docker-net:5432/mlflow?sslmode=disable

  mlflow:
    image: custom-mlflow
    container_name: mlflow
    env_file:
      - .env.build
    build:
      context: ./configs/mlflow
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - mlflow_data:/mlflow
    networks:
      - docker-net
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.mlflow-http.rule=Host(`mlflow.localhost`)
      - traefik.http.routers.mlflow-http.entrypoints=web

  opinionlens:
    image: opinionlens
    container_name: opinionlens
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    networks:
      - docker-net
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.opinionlens-http.rule=Host(`opinionlens.localhost`)
      - traefik.http.routers.opinionlens-http.entrypoints=web
      - traefik.http.middlewares.opinionlens-ratelimit.ratelimit.average=5
      - traefik.http.middlewares.opinionlens-ratelimit.ratelimit.period=1s
      - traefik.http.middlewares.opinionlens-ratelimit.ratelimit.burst=10
      - traefik.http.routers.opinionlens-http.middlewares=opinionlens-ratelimit@docker

  traefik:
    image: traefik:v3.6.5
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
    networks:
      - docker-net
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-http.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik-http.entrypoints=web

  node-exporter:
    privileged: true
    image: prom/node-exporter:master
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      - '--collector.cgroups'
    networks:
      - docker-net
    pid: host
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    networks:
      - docker-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus-http.rule=Host(`prometheus.localhost`)
      - traefik.http.routers.prometheus-http.entrypoints=web

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env.build
    expose:
      - 3000
    networks:
      - docker-net
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./configs/grafana/datasources:/etc/grafana/provisioning/datasources/
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana-http.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana-http.entrypoints=web

networks:
  docker-net:
    external: true

volumes:
  prometheus_data: {}
  postgres_data: {}
  mlflow_data: {}
  grafana_data: {}
