stages:
  preprocess_data:
    cmd: mkdir -p ./data/preprocessed && uv run preprocess_data
    deps:
      - src/opinionlens/preprocessing/scripts/preprocess_data.py
      - src/opinionlens/preprocessing/clean.py
      - src/opinionlens/preprocessing/tokenize.py
      - data/raw/IMDB Dataset/
      - data/raw/Amazon Food Reviews/
    params:
      - preprocessing.data_splits
    outs:
      - data/preprocessed/imdb_dataset/
      - data/preprocessed/amazon_food_reviews/

  vectorize_data:
    cmd: mkdir -p ./data/vectorized && uv run vectorize_data
    deps:
      - src/opinionlens/preprocessing/scripts/vectorize_data.py
      - src/opinionlens/preprocessing/vectorize.py
      - data/preprocessed/
    outs:
      - data/vectorized/

  run_baselines:
    cmd: uv run baselines
    deps:
      - data/preprocessed/
    always_changed: true

  train_sklearn:
    cmd: uv run train_sklearn
    deps:
      - data/vectorized/
    always_changed: true

  tune_sklearn:
    cmd: uv run tune_sklearn
    deps:
      - data/vectorized/
    always_changed: true
