stages:
  preprocess_data:
    cmd: mkdir -p ./data/preprocessed && uv run python -m src.preprocessing.scripts.preprocess_data
    deps:
      - src/preprocessing/scripts/preprocess_data.py
      - src/preprocessing/clean.py
      - src/preprocessing/tokenize.py
      - data/raw/IMDB Dataset/
    params:
      - preprocessing.data_splits
    outs:
      - data/preprocessed/imdb_dataset/

  vectorize_data:
    cmd: mkdir -p ./data/vectorized && uv run python -m src.preprocessing.scripts.vectorize_data
    deps:
      - src/preprocessing/scripts/vectorize_data.py
      - src/preprocessing/vectorize.py
      - data/preprocessed/
    outs:
      - data/vectorized/

  run_baselines:
    cmd: uv run python -m src.training.baselines
    deps:
      - src/training/baselines.py
      - data/preprocessed/
      - .env.dev
